// Energy data with image URLs
const energyData = {
    solar: {
        title: "Solar Energy",
        image: "solarenergy.webp",
        description: `
            <p>Solar energy is harnessed from the sun's radiation using photovoltaic cells or solar thermal systems. It's a renewable, clean energy source that produces no greenhouse gas emissions during operation.</p>
            
            <h3>How It Works</h3>
            <p>Photovoltaic cells convert sunlight directly into electricity through the photovoltaic effect. When sunlight hits the semiconductor material in the cells, it knocks electrons loose, allowing them to flow freely and generate an electric current.</p>
            
            <h3>Advantages</h3>
            <p>Solar energy is abundant, renewable, and produces no air pollution or greenhouse gases. Solar panels have no moving parts and require minimal maintenance once installed.</p>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-value">1.73×10⁵</div>
                    <div class="stat-label">TW Solar Energy Reaching Earth</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">20-25%</div>
                    <div class="stat-label">Typical Efficiency</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">3-8 years</div>
                    <div class="stat-label">Energy Payback Time</div>
                </div>
            </div>
        `
    },
    wind: {
        title: "Wind Energy",
        image: "wind.webp",
        description: `
            <p>Wind energy is generated by converting the kinetic energy of wind into mechanical power using wind turbines. This mechanical power can be used for specific tasks or converted to electricity.</p>
            
            <h3>How It Works</h3>
            <p>Wind turns the propeller-like blades of a turbine around a rotor, which spins a generator to create electricity. The wind's kinetic energy is converted into mechanical power as the blades rotate, which then drives the generator.</p>
            
            <h3>Advantages</h3>
            <p>Wind power is a clean, renewable energy source with no emissions. It's one of the lowest-priced renewable energy technologies available today and can be built on existing farms or ranches.</p>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-value">2-3 MW</div>
                    <div class="stat-label">Typical Turbine Capacity</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">35-45%</div>
                    <div class="stat-label">Capacity Factor</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">6-9 months</div>
                    <div class="stat-label">Energy Payback Time</div>
                </div>
            </div>
        `
    },
    hydro: {
        title: "Hydroelectric Power",
        image: "hydropower.jpg",
        description: `
            <p>Hydroelectric power is generated by harnessing the energy of flowing or falling water. It's one of the oldest and largest sources of renewable energy.</p>
            
            <h3>How It Works</h3>
            <p>Water stored in a reservoir behind a dam flows through turbines, spinning them, which in turn activates generators to produce electricity. The amount of electricity generated depends on the volume of water flow and the height difference between the source and the water's outflow.</p>
            
            <h3>Advantages</h3>
            <p>Hydroelectric power is a clean, renewable source with very low greenhouse gas emissions. It provides a consistent and reliable power source and reservoirs can also offer recreational opportunities.</p>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-value">~71%</div>
                    <div class="stat-label">Of Renewable Electricity</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">90%</div>
                    <div class="stat-label">Efficiency Rate</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">50-100 years</div>
                    <div class="stat-label">Plant Lifespan</div>
                </div>
            </div>
        `
    },
    fossil: {
        title: "Fossil Fuel Power",
        image: "fosels.webp",
        description: `
            <p>Fossil fuel power plants generate electricity by burning coal, oil, or natural gas. These are non-renewable energy sources formed from the remains of ancient plants and animals.</p>
            
            <h3>How It Works</h3>
            <p>Fossil fuels are burned in a combustion chamber to produce high-pressure steam. This steam drives turbines connected to generators, producing electricity. The steam is then condensed back into water and returned to the system.</p>
            
            <h3>Environmental Impact</h3>
            <p>Fossil fuel combustion releases significant amounts of carbon dioxide and other greenhouse gases, contributing to climate change. They also produce air pollutants that can harm human health and the environment.</p>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-value">~64%</div>
                    <div class="stat-label">Global Electricity</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">33-40%</div>
                    <div class="stat-label">Typical Efficiency</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">2.2B Tons</div>
                    <div class="stat-label">CO₂/Year from Coal</div>
                </div>
            </div>
        `
    },
    nuclear: {
        title: "Nuclear Power",
        image: "nuclear-power-plant.webp",
        description: `
            <p>Nuclear power is generated through nuclear fission, where atoms are split to release energy. This energy heats water to produce steam that drives turbines connected to generators.</p>
            
            <h3>How It Works</h3>
            <p>In a nuclear reactor, uranium atoms are split in a controlled chain reaction. The heat produced from this reaction is used to create steam from water. The steam then spins large turbines that are connected to generators, producing electricity.</p>
            
            <h3>Advantages & Challenges</h3>
            <p>Nuclear power produces massive amounts of energy with minimal greenhouse gas emissions. However, it creates radioactive waste that must be safely stored for thousands of years and carries risks of accidents.</p>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-value">~10%</div>
                    <div class="stat-label">Global Electricity</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">92%</div>
                    <div class="stat-label">Capacity Factor</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">24/7</div>
                    <div class="stat-label">Reliable Operation</div>
                </div>
            </div>
        `
    }
};

// Main Energy Visualization class
class EnergyVisualization {
    constructor() {
        this.currentEnergyType = 'solar';
        this.canvasContainer = document.querySelector('.canvas-container');
        
        this.init();
        this.setupEventListeners();
    }
    
    init() {
        // Clear the canvas container and add image display area
        this.canvasContainer.innerHTML = '';
        
        // Create image container
        this.imageContainer = document.createElement('div');
        this.imageContainer.className = 'image-container';
        this.imageContainer.style.width = '100%';
        this.imageContainer.style.height = '100%';
        this.imageContainer.style.display = 'flex';
        this.imageContainer.style.alignItems = 'center';
        this.imageContainer.style.justifyContent = 'center';
        this.imageContainer.style.overflow = 'hidden';
        this.imageContainer.style.borderRadius = '15px';
        this.imageContainer.style.position = 'relative';
        
        // Create main energy image
        this.energyImage = document.createElement('img');
        this.energyImage.src = energyData[this.currentEnergyType].image;
        this.energyImage.alt = energyData[this.currentEnergyType].title;
        this.energyImage.style.width = '100%';
        this.energyImage.style.height = '100%';
        this.energyImage.style.objectFit = 'cover';
        this.energyImage.style.borderRadius = '15px';
        this.energyImage.style.transition = 'opacity 0.5s ease-in-out';
        
        // Create image caption
        this.imageCaption = document.createElement('div');
        this.imageCaption.className = 'image-caption';
        this.imageCaption.textContent = energyData[this.currentEnergyType].title;
        this.imageCaption.style.position = 'absolute';
        this.imageCaption.style.bottom = '20px';
        this.imageCaption.style.left = '20px';
        this.imageCaption.style.right = '20px';
        this.imageCaption.style.background = 'rgba(0, 0, 0, 0.7)';
        this.imageCaption.style.color = 'white';
        this.imageCaption.style.padding = '10px 15px';
        this.imageCaption.style.borderRadius = '8px';
        this.imageCaption.style.fontSize = '1.2rem';
        this.imageCaption.style.fontWeight = 'bold';
        this.imageCaption.style.backdropFilter = 'blur(5px)';
        
        this.imageContainer.appendChild(this.energyImage);
        this.imageContainer.appendChild(this.imageCaption);
        this.canvasContainer.appendChild(this.imageContainer);
        
        // Update info panel with initial data (without image)
        this.updateInfoPanel(this.currentEnergyType);
    }
    
    setupEventListeners() {
        // Energy type buttons
        const energyButtons = document.querySelectorAll('.energy-btn');
        energyButtons.forEach(button => {
            button.addEventListener('click', () => {
                // Update active button
                energyButtons.forEach(btn => btn.classList.remove('active'));
                button.classList.add('active');
                
                // Update energy type
                const energyType = button.getAttribute('data-energy');
                this.currentEnergyType = energyType;
                
                // Update image and caption
                this.updateImage(energyType);
                
                // Update info panel
                this.updateInfoPanel(energyType);
            });
        });
        
        // Handle window resize
        window.addEventListener('resize', () => this.onWindowResize());
    }
    
    updateImage(energyType) {
        const data = energyData[energyType];
        
        // Add fade out effect
        this.energyImage.style.opacity = '0';
        this.imageCaption.style.opacity = '0';
        
        setTimeout(() => {
            // Update image and caption
            this.energyImage.src = data.image;
            this.energyImage.alt = data.title;
            this.imageCaption.textContent = data.title;
            
            // Add fade in effect
            this.energyImage.style.opacity = '1';
            this.imageCaption.style.opacity = '1';
        }, 250);
    }
    
    updateInfoPanel(energyType) {
        const data = energyData[energyType];
        document.getElementById('energy-title').textContent = data.title;
        document.getElementById('energy-description').innerHTML = data.description;
        
        // Remove any existing image from info panel
        const existingImage = document.getElementById('energy-image');
        if (existingImage) {
            existingImage.remove();
        }
    }
    
    onWindowResize() {
        // Adjust image container size if needed
        const container = document.querySelector('.canvas-container');
        this.imageContainer.style.width = container.clientWidth + 'px';
        this.imageContainer.style.height = container.clientHeight + 'px';
    }
    
    // Method to add custom energy source
    addEnergySource(key, title, imageUrl, description) {
        energyData[key] = {
            title: title,
            image: imageUrl,
            description: description
        };
        
        // Add new button to the selector
        const energySelector = document.querySelector('.energy-selector');
        const newButton = document.createElement('button');
        newButton.className = 'energy-btn';
        newButton.setAttribute('data-energy', key);
        newButton.textContent = title;
        
        // Add event listener to new button
        newButton.addEventListener('click', () => {
            document.querySelectorAll('.energy-btn').forEach(btn => btn.classList.remove('active'));
            newButton.classList.add('active');
            this.currentEnergyType = key;
            this.updateImage(key);
            this.updateInfoPanel(key);
        });
        
        energySelector.appendChild(newButton);
    }
    
    // Method to update existing energy source
    updateEnergySource(key, newData) {
        if (energyData[key]) {
            energyData[key] = { ...energyData[key], ...newData };
            
            // If this is the current energy type, update the display
            if (this.currentEnergyType === key) {
                this.updateImage(key);
                this.updateInfoPanel(key);
            }
        }
    }
    
    // Method to get all energy sources
    getAllEnergySources() {
        return Object.keys(energyData);
    }
    
    // Method to get specific energy source data
    getEnergySource(key) {
        return energyData[key];
    }
}

// Initialize the visualization when the page loads
window.addEventListener('DOMContentLoaded', () => {
    const energyViz = new EnergyVisualization();
    
    // Make energyViz globally available for console manipulation
    window.energyViz = energyViz;
});